POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "1d8a26d2-5937-4dfb-b656-705128848622"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a9a03a9d-798f-4691-9468-b9a3d00c25c0",
    "account_id_to": "337366f7-c78b-4ef5-aa3e-54fdfb73f2b3",
    "amount": 10
}